# Generated by Django 5.1.1 on 2025-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
