# Generated by Django 5.1.1 on 2025-02-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderitem_order_alter_orderitem_quantity"),
        ("products", "0006_remove_banner_product_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="IPhoneVariant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="products.iphonevariant",
            ),
        ),
    ]
