# Generated by Django 5.1.1 on 2025-02-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=30, unique=True)),
                ("color_hex", models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IPhoneSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "iPhone Series",
                "verbose_name_plural": "iPhone Series",
            },
        ),
        migrations.CreateModel(
            name="StorageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IPhoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "display_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("color_options", models.ManyToManyField(to="products.coloroption")),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="products.iphoneseries",
                    ),
                ),
                (
                    "storage_options",
                    models.ManyToManyField(to="products.storageoption"),
                ),
            ],
            options={
                "verbose_name": "iPhone Model",
                "verbose_name_plural": "iPhone Models",
                "unique_together": {("series", "name")},
            },
        ),
        migrations.CreateModel(
            name="IPhoneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("refurbished", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="iphone_images/"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.coloroption",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.iphonemodel",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.storageoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "iPhone Variant",
                "verbose_name_plural": "iPhone Variants",
                "unique_together": {("model", "storage", "color")},
            },
        ),
    ]
