# Generated by Django 5.1.1 on 2025-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_banner_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="iphonevariant",
            name="max_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
